# Generated by Django 2.1.5 on 2019-01-26 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now=True)),
                ('due_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('gender', models.TextField(max_length=1)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Name')),
                ('genres', models.TextField(default='')),
                ('length', models.IntegerField(default=0)),
                ('cover', models.FileField(upload_to='covers')),
                ('year', models.IntegerField(default=0)),
                ('country', models.TextField(default='')),
                ('in_stock', models.IntegerField()),
                ('borrow_price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='borroworder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='movieloanapp.Customer'),
        ),
        migrations.AddField(
            model_name='borroworder',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='movieloanapp.Movie'),
        ),
    ]
