# Generated by Django 2.1.5 on 2019-01-27 15:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('genres', models.CharField(default='', max_length=50)),
                ('length', models.IntegerField(default=0, verbose_name='Duration')),
                ('cover', models.FileField(upload_to='covers')),
                ('year', models.IntegerField(default=0)),
                ('country', models.CharField(default='', max_length=50)),
                ('in_stock_qty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='In stock quantity')),
                ('borrow_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(default='RENTED', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='movieloanapp.Customer')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='movieloanapp.Movie')),
            ],
        ),
    ]
