# Generated by Django 2.1.5 on 2019-01-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieloanapp', '0003_auto_20190126_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='movie',
            name='in_stock_qty',
            field=models.IntegerField(default=0, verbose_name='In stock quantity'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.IntegerField(default=0, verbose_name='Duration'),
        ),
    ]
